export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";
export const ACQUIRER_MERCHANT = "ACQUIRER_MERCHANT";
export const ACQUIRER_MERCHANT_PROPOSAL = "ACQUIRER_MERCHANT_PROPOSAL";
export const CARTA_CIRCULARIZACAO_SINTETICA = "CARTA_CIRCULARIZACAO_SINTETICA";